services:
  preview-server:
    container_name: server
    image: project/server:preview
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    healthcheck:
      test: curl -f localhost/health || exit 1
      interval: 1m
    volumes:
      - preview_files_volume:/var/www/files
      # make logs accessible to fail2ban in host
      - /var/log/nginx:/var/log/nginx:rw
    networks:
      - main_network
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp

  preview-db:
    container_name: db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=project
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    healthcheck:
      test: pg_isready -d project
      interval: 1m
    volumes:
      - preview_db_volume:/var/lib/postgresql/data
    networks:
      - main_network

  preview-redis:
    container_name: redis
    image: redis:7.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m
    volumes:
      - preview_redis_volume:/data
    networks:
      - main_network

  preview-api:
    container_name: api
    image: project/api:preview
    env_file:
      - .env.preview
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    healthcheck:
      # simple node
      test: wget -qO- localhost:3000/health || exit 1
      interval: 1m
    volumes:
      - preview_files_volume:/usr/src/app/files
    networks:
      - main_network
    depends_on:
      - preview-db
      - preview-redis

  preview-web:
    container_name: web
    image: project/web:preview
    deploy:
      #replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    healthcheck:
      # sveltekit
      test: wget -qO- 0.0.0.0:3000/health || exit 1
      interval: 1m
    networks:
      - main_network
    depends_on:
      - preview-api

  preview-cms:
    container_name: cms
    image: project/cms:preview
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    healthcheck:
      # sveltekit
      test: wget -qO- 0.0.0.0:3000/health || exit 1
      interval: 1m
    networks:
      - main_network
    depends_on:
      - preview-api

networks:
  main_network:
    name: main_network
    driver: bridge

volumes:
  preview_files_volume:
    name: files
  preview_db_volume:
    name: db
  preview_redis_volume:
    name: redis_volume
